# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebird/base/base_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66irebird/base/base_test.proto\x12\rfirebird.base\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"@\n\tTestState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x04test\x18\x02 \x01(\x0e\x32\x17.firebird.base.TestEnum\"\xc8\x01\n\x0eTestCollection\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05tests\x18\x02 \x03(\x0b\x32\x18.firebird.base.TestState\x12(\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12+\n\nannotation\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\nsupplement\x18\x05 \x03(\x0b\x32\x14.google.protobuf.Any*\xd8\x01\n\x08TestEnum\x12\x10\n\x0cTEST_UNKNOWN\x10\x00\x12\x0e\n\nTEST_READY\x10\x01\x12\x10\n\x0cTEST_RUNNING\x10\x02\x12\x10\n\x0cTEST_WAITING\x10\x03\x12\x12\n\x0eTEST_SUSPENDED\x10\x04\x12\x11\n\rTEST_FINISHED\x10\x05\x12\x10\n\x0cTEST_ABORTED\x10\x06\x12\x10\n\x0cTEST_CREATED\x10\x01\x12\x10\n\x0cTEST_BLOCKED\x10\x03\x12\x10\n\x0cTEST_STOPPED\x10\x04\x12\x13\n\x0fTEST_TERMINATED\x10\x06\x1a\x02\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firebird.base.base_test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTENUM._options = None
  _TESTENUM._serialized_options = b'\020\001'
  _globals['_TESTENUM']._serialized_start=375
  _globals['_TESTENUM']._serialized_end=591
  _globals['_TESTSTATE']._serialized_start=105
  _globals['_TESTSTATE']._serialized_end=169
  _globals['_TESTCOLLECTION']._serialized_start=172
  _globals['_TESTCOLLECTION']._serialized_end=372
# @@protoc_insertion_point(module_scope)
